### ISSUE TITLE
Android crash java.lang.ClassNotFoundException

### ISSUE THREAD

**Issue by SebastianSingle99** [PiwikPRO/react-native-piwik-pro-sdk#41]
Seems to be the same issue like here:

https://github.com/terveystalo/react-native-piwik-pro-sdk/issues/39
https://github.com/terveystalo/react-native-piwik-pro-sdk/pull/40

`com.google.android.gms:play-services-ads-identifier` should be listed as dependency.

**Comment by sanderwapstra** [comment]
Adding `implementation "com.google.android.gms:play-services-ads-identifier:18.0.1"` under `dependencies` to `/android/app/build.gradle` fixes this crash for now.
