### ISSUE TITLE
Android build error Gradle plugin supports only Kotlin Gradle plugin version 1.5.20 and higher on React-Native 0.71.3 targeting Android API 33.

### ISSUE THREAD

**Issue by padabala** [PiwikPRO/react-native-piwik-pro-sdk#53]
* What went wrong:
The Android Gradle plugin supports only Kotlin Gradle plugin version 1.5.20 and higher.
The following dependencies do not satisfy the required version:
project ':piwikpro_react-native-piwik-pro-sdk' -> org.jetbrains.kotlin:kotlin-gradle-plugin:1.3.50

"react": "18.2.0",
"react-native": "0.71.3"

Gradle: 
buildToolsVersion = "33.0.0"
minSdkVersion = 21
compileSdkVersion = 33
targetSdkVersion = 33

**Comment by 4teko7** [comment]
To fix this problem, in android/gradle.properties :
 PiwikProSdk_kotlinVersion=1.3.50 => PiwikProSdk_kotlinVersion=X (The compatible version of kotlin. In my case it is: 1.6.0)
